# ==============================================================================
# MULTI-STAGE DOCKERFILE PARA BACKEND API & WORKER
# ==============================================================================

FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ------------------------------------------------------------------------------
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/database/seeds ./src/database/seeds

EXPOSE 8000

CMD ["node", "dist/main.js"]
